stages:
  - build
  - test

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

services:
  - docker:dind

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  image: benediktg/docker-java8-openjfx
  script:
    - ./gradlew makeInstall
  artifacts:
    paths:
      - lapras-agents/build/install/*
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  image: benediktg/docker-java8-openjfx
  script:
    - ./gradlew check
    
after_script:
  - echo "End CI"