version: "3.8"  # Docker 27.5.1이므로 최신 버전 사용 가능

services:
  lapras_app:
    build:
      context: .                               # docker-compose.yml이 있는 위치를 빌드 컨텍스트로 사용
      dockerfile: dockerfiles/base.Dockerfile   # dockerfile 경로 지정
    container_name: lapras_container
    restart: unless-stopped
    volumes:                                   # 서버의 middleware, agents, utils 디렉토리를 컨테이너 내부 /app에 마운트
      - ./middleware:/app/middleware
      - ./agents:/app/agents
      - ./utils:/app/utils
      - ./requirements:/app/requirements
    ports:                                     # 8080 포트 개방
      - "8080:8080"
    environment:                               # 환경 변수 설정
      - LAPRAS_HOME=/app
      - LAPRAS_LOG_LEVEL=INFO
      - CONFIG_URL=http://lapras.kaist.ac.kr/conf/default.conf
    #command: ["python", "-m", "middleware.core.agent"]  # 아직 미구현
    command: ["bash"]

